### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mariokeks** [GeorgeRiley/sm-ext-SoundscapeHook#1]
I already tried sig scanning on my own but Im really too inexperienced
would be great if you could help with that or release a windows version

**Comment by rtldg** [comment]
a good alternative you could try out is https://github.com/Haze1337/Sound-Manager which hooks UpdateForPlayer via dhooks2

**Comment by mariokeks** [comment]
thanks! i already tested it, it works like a charm!
